config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#show'
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]

  #No route matches [DELETE] "/relationships" fuck you haha
  delete  "relationships" => "relationships#destroy"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  title           :string
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#  picture         :string
#  likes_count     :integer          default("0")
#  published_at    :datetime
#  featured        :boolean          default("false")
#  lead            :text
#  slug            :string
#  responses_count :integer          default("0"), not null
#

class Post < ActiveRecord::Base

  validates :title, :body, :user_id, presence: true

  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :responses, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :responders, through: :responses, source: :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :bookmarks, as: :bookmarkable, dependent: :destroy
  has_many :bookmarkers, through: :bookmarks, source: :user

  delegate :username, to: :user

  scope :recent, -> { order(created_at: :desc) }
  scope :latest, ->(number) { recent.limit(number) }
  scope :top_bonga, ->(number) { order(likes_count: :desc).limit(number) }
  scope :published, -> { where.not(published_at: nil) }
  scope :drafts, -> { where(published_at: nil) }
  scope :featured, -> { where(featured: true) }

  mount_uploader :picture, PictureUploader

  before_save :generate_lead!
  # will_pagination configuration
  self.per_page = 5

  include SearchablePost

  extend FriendlyId
  friendly_id :title, use: [ :slugged, :history, :finders ]

  def self.new_draft_for(user)
    post = self.new(user_id: user.id)
    post.save_as_draft
    post
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def related_posts(size: 3)
    Post.joins(:taggings).where.not(id: self.id).where(taggings: { tag_id: self.tag_ids }).distinct.
      published.limit(size).includes(:user)
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.first_or_create_with_name!(name)
    end
    RelatedTagsCreator.create(self.tag_ids)
  end

  def all_tags
    tags.map(&:name).join(", ")
  end

  def publish
    self.published_at = Time.zone.now
    self.slug = nil # let FriendlyId generate slug
    save
  end

  def save_as_draft
    self.published_at = nil
    self.slug ||= SecureRandom.urlsafe_base64
    save(validate: false)
  end

  def unpublish
    self.published_at = nil
  end

  def published?
    published_at.present?
  end

  def words
    body.split(' ')
  end

  def word_count
    words.size
  end

  # Generate a lead which appears in post panel.
  # FIXME: this method needs refactoring or completely different approach
  def generate_lead!
    if self.published?
      post_body = Nokogiri::HTML::Document.parse(self.body)
      if post_body.css('h2').size > 0
        self.lead = post_body.css('h2')[0].to_s
      elsif post_body.css('h3').size > 0
        self.lead = post_body.css('h3')[0].to_s
      elsif post_body.css('p').size > 0
        self.lead = post_body.css('p')[0].to_s
      end
    end
  end

end

app/controllers/api/posts/bookmarks_controller.rb
class API::Posts::BookmarksController < API::BookmarksController

  private

    def set_bookmarkable
      @bookmarkable = Post.find(params[:post_id])
    end
end

app/controllers/api/posts/likes_controller.rb
class API::Posts::LikesController < API::LikesController

  private

    def set_likeable
      @likeable = Post.find(params[:post_id])
    end
end

app/controllers/api/posts_controller.rb
class API::PostsController < ApplicationController
  before_action :authenticate_user!

  def update
    @post = current_user.posts.find(params[:id])
    @post.assign_attributes(post_params)
    if @post.published?
      @post.save
    else
      @post.save_as_draft
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, :all_tags, :picture)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  layout "editor", only: [:new, :edit, :create, :update]

  def show
    @post = Post.find(params[:id])
    @responses = @post.responses.includes(:user)
    @related_posts = @post.related_posts
    # If an old id or a numeric id was used to find the record, then
    # the request path will not match the post_path, and we should do
    # a 301 redirect that uses the current friendly id.
    if request.path != post_path(@post)
      redirect_to @post, status: 301
    end
  end

  def new
    @post = Post.new_draft_for(current_user)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.publish
      redirect_to @post, notice: "Successfully published your bonga!"
    else
      @post.unpublish
      flash.now[:alert] = "Could not update the post, Please try again"
      render :new
    end
  end

  def edit
  end

  def update
    @post.assign_attributes(post_params)
    if @post.publish
      redirect_to @post, notice: "Successfully published your bonga!"
    else
      @post.unpublish
      flash.now[:alert] = "Could not update the post, Please try again"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_url, notice: "Successfully deleted your bonga!"
  end

  # TODO: ideally move this to a separate controller?
  def create_and_edit
    @post = current_user.posts.build(post_params)
    @post.save_as_draft
    redirect_to edit_post_url(@post)
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, :all_tags, :picture)
    end

    def authorize_user
      begin
        @post = current_user.posts.find(params[:id])
      rescue
        redirect_to root_url
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_length_in_minutes(body)
    min = body.split(" ").size / 250
    if min == 0
      'less than a minute read'
    else
      "#{min} min read"
    end
  end

  # blacklisting
  def remove_javascript(html)
    html.gsub(/<script.*?>/i, "")
        .gsub(/<\/script>/i, "")
        .gsub(/javascript:/i, "")
        .gsub(/on[\w]+=/i, "")
  end

  # whitelisting
  # TODO: this won't work for embedded video
  def sanitize_html(html)
    sanitize(html, tags: %w(p b i u blockquote br h2 h3 div a img figure figcaption iframe html),
             attributes: %w(class href style))
  end
end

app/views/posts/_bookmarks.html.erb
<div class="bookmark-button-wrapper">
  <% if user_signed_in? %>
    <%= react_component('BookmarkButton', 
    { bookmarked: current_user.bookmarked?(post),
      bookmarkEndpoint: api_post_bookmarks_path(post),
      unbookmarkEndpoint: api_post_bookmarks_path(post),
      bookmarkableType: 'Post',
      bookmarkableId: post.id }) %>
  <% else %>
    <%= button_to '', method: :get, class: 'bookmark-button', data: { behavior: 'trigger-overlay' } do %>
      <span class="icon-bookmark-o"></span><span class="hide-text">Bookmark</span>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for post, html: { multipart: true, class: "editor-form", data: { page: 'main-editor' }, autocomplete: "off" } do |f| %>

  <label class="picture_upload">
    <%= f.file_field :picture %>
    <i class="fa fa-camera"></i>
  </label>
  <div class="file-upload-previewer hidden">
    <img src="" id="image_preview"/>
  </div>
  <% if post.picture? %>
    <div class="existing-img-previewer" id="existing-img-previewer">
      <%= image_tag post.picture.url(:thumb) %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: 'editor-title', placeholder: 'Title', autofocus: true, data: { behavior: "autosave" }, onfocus: "this.value = this.value;" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'medium-editable', data: { behavior: "autosave" } %> 
  </div>

  <div class="hidden">
    <%= f.text_field :all_tags %>
  </div>

<% end %>

app/views/posts/_likes.html.erb
<div class="like-button-wrapper">
  <% if user_signed_in? %>
    <%= react_component('LikeButton',
                        { liked: current_user.liked?(post),
                          likeCount: post.likes.size,
                          likeEndpoint: api_post_likes_path(post),
                          unlikeEndpoint: api_post_likes_path(post),
                          likeableType: 'Post',
                          likeableId: post.id,
                          overlayHeading: "People liked #{post.title}",
                          overlayEndpoint: api_likers_path(post_id: post.id)}) %>
  <% else %>
    <%= button_to '', method: :get, class: 'like-button', data: { behavior: 'trigger-overlay' } do %>
      <i class="fa fa-heart-o"></i><span class="hide-text">Like</span>
    <% end %>
    <span class="like-count"><%= post.likes.size %></span>
  <% end %>
</div>

app/views/posts/_metadata_bar.html.erb
<div class="post-metadata-bar" data-page="post-metadata-bar">
  <div class="flex-container" data-behavior="animated-metadata">
    <div class="post-stats flex-container">
      <%= render partial: 'posts/likes', locals: { post: post } %>

      <div>
        <%= link_to post_path(post, anchor: 'responses'), class: "response-icon-wrapper" do %>
          <i class="fa fa-comment-o"></i>
          <span class="response-count" data-behavior="response-count"><%= post.responses.size %></span>
        <% end %>
      </div>

      <div class="bookmark-button">
        <%= render partial: 'posts/bookmarks', locals: { post: post } %>
      </div>
    </div>
    <div class="metabar-author-info flex-container flex-space-btw">
      <div>
        <%= avatar_for post.user, size: 35 %>
        <%= react_component("PopoverLink", { user_id: post.user.id, url: user_path(post.user), children: post.username }) %>
      </div>
      <%= follow_button_for post.user %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="post-panel">
  <%= render partial: 'posts/post_metadata', locals: { post: post } %>

  <% if post.picture? %>
    <div class="post-picture-wrapper">
      <%= image_tag post.picture.url(:thumb) %>
    </div>
  <% end %>

  <div class="main-body">
    <h3 class="post-title"><%= link_to post.title, post %></h3>
    <% if post.lead %>
      <div class="post-body"><%= truncate(remove_javascript(post.lead), length: 140, separator: ' ', escape: false) %></div>
      <%= link_to "Read more", post, class: 'read-more' %>
    <% end %>
  </div>

  <div class="post-stats clearfix">
    <div class="pull-left">
      <%= render partial: 'posts/likes', locals: { post: post } %>
    </div>

    <div class="pull-right">
      <%= render partial: 'posts/bookmarks', locals: { post: post } %>
    </div>

    <div class="response-count pull-right">
      <% if post.responses_count > 0 %>
        <%= link_to (pluralize(post.responses_count, "response")), post_path(post, anchor: 'responses'), class: 'response-count' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post_list_item.html.erb
<div class="post-list-item">
  <div class="flex-container">
    <div class="avatar-wrapper">
      <%= avatar_for(post.user, size: 40) %>
    </div>
    <div class="post-info">
      <strong class="pli-title"><%= link_to post.title, post %></strong><br/>
      <small class="pli-username"><%=link_to post.username, post.user %></small>
    </div>
    <% if post.picture? %>
      <div class="pli-picture-wrapper">
        <%= image_tag post.picture.url(:thumb) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post_metadata.html.erb
<div class="post-metadata">
  <%= avatar_for post.user, size: 40 %>
  <div class="post-info">
    <%= react_component("PopoverLink", { user_id: post.user.id, url: user_path(post.user), children: post.username }) %>
    <small><%= time_ago_in_words(post.created_at) %> ago &#149; <%= post_length_in_minutes(post.body) %></small>
  </div>
</div>

app/views/posts/_response_editor.html.erb
<div class="inline-editor" data-behavior="response-editor" >
  <div class="editor-metadata">
    <%= avatar_for(current_user, size: 40) %>
    <strong class="editor-username"><%= current_user.username %></strong>
  </div>
  <%= form_for [post, Response.new], remote: true, html: { class: 'editor-form' } do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class: "medium-editable response-body", id: 'editor-body' %>
    </div>
    <%= f.submit "Publish", class: 'button green-inner-button' %>
    <button class='button green-border-button cancel-button' data-behavior="editor-cancel">Cancel</button>
  <% end %>
</div>

app/views/posts/_social_share.html.erb
<div class="social-share-wrapper">
  <div class="social-share">
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= post_url(post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)"
       class="ico fb">
       <i class="fa fa-facebook"></i>
    </a>
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= post.title %> by <%= post.username %> - &amp;url=<%= post_url(post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)"
       class="ico tw">
       <i class="fa fa-twitter"></i>
    </a>
    <a onclick="javascript:window.open('http://plus.google.com/share?url=<%= post_url(post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)"
       class="ico gp">
       <i class="fa fa-google-plus"></i>
    </a>
    <span class="text"><em>SHARE</em></span>
    <span class="ico-share"><i class="fa fa-share-alt"></i></span>
  </div>
</div>

app/views/posts/_top_stories.html.erb
<% posts.each_with_index do |post, index| %>
  <div class="post-panel">
    <div class="top-story-rank">
      <div class="count-button-wrapper">
        <span class="count-button"><%= index + 1 %></span>
      </div>
    </div>
    <%= render partial: 'posts/post_metadata', locals: { post: post } %>

    <% if post.picture? %>
      <div class="post-picture-wrapper">
        <%= image_tag post.picture.url(:thumb) %>
      </div>
    <% end %>

    <div class="main-body">
      <h3 class="post-title"><%= link_to post.title, post %></h3>
      <% if post.lead %>
        <div class="post-body"><%= truncate(post.lead, length: 190, separator: ' ', escape: false) %></div>
        <%= link_to "Read more", post, class: 'read-more' %>
      <% end %>
    </div>

    <div class="post-stats clearfix">
      <div id="post_<%= post.id %>_likes" class="pull-left">
        <%= render partial: 'posts/likes', locals: { post: post } %>
      </div>

      <div id="post_<%= post.id %>_bookmarks" class="pull-right">
        <%= render partial: 'posts/bookmarks', locals: { post: post } %>
      </div>

      <div class="response-count pull-right">
        <% if post.responses_count > 0 %>
          <%= link_to (pluralize(post.responses_count, "response")), post_path(post, anchor: 'responses'), class: 'response-count' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div data-animation="fadeInUp-fadeOutDown">
  <div class="col-xs-10 col-sm-10 col-md-6 col-md-offset-3 col-sm-offset-1 col-xs-offset-1">
    <div class="post-metadata">
      <%= avatar_for(current_user, size: 40) %>
      <div class="post-info">
        <%= link_to current_user.username, current_user %><br/>
        <small>Edit Post</small>
      </div>
    </div>
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<!-- new posts for logged in users -->
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<div class="error">
	<h2>
		<%= pluralize(@post.errors.count, "errors") %>
		prohibited this post from being saved:
	</h2>
	<ul>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<!-- new post -->

<% end %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.label :all_tags %>
<%= f.text_field :all_tags %>

<%= f.submit "Publish" %>
<% end %>

app/views/posts/show.html.erb
<div class="row" data-animation="fadeInUp-fadeOutDown">
  <div id="main-post" class="col-xs-10 col-md-8 col-md-offset-2 col-xs-offset-1 main-content">
    <% if admin_signed_in? %>
      <%= feature_post_button_for(@post) %>
    <% end %>

    <div class="pull-right">
      <%= render partial: 'posts/social_share', locals: { post: @post } %>
    </div>
    <%= render 'post_metadata', post: @post %>

    <% if @post.picture? %>
      <div class="post-picture-wrapper">
        <%= image_tag @post.picture.url(:thumb) %>
      </div>
    <% end %>

    <h3 class="title"><%= @post.title %></h3>
    <div class="body">
      <p><%= remove_javascript(@post.body).html_safe %></p>
    </div>

    <div class="post-tags">
      <% @post.tags.each do |tag| %>
        <%= link_to tag.name, tag, class: 'tag' %>
      <% end %>
    </div>

    <div class="post-stats clearfix">
      <div class="pull-left">
        <%= render partial: 'posts/likes', locals: { post: @post } %>
      </div>
      <div class="pull-left">
        <%= link_to post_path(@post, anchor: 'responses'), class: "response-icon-wrapper" do %>
          <i class="fa fa-comment-o"></i>
          <span class="response-count" data-behavior="response-count"><%= @post.responses_count %></span>
        <% end %>
      </div>

      <div class="pull-right">
        <%= render partial: 'posts/bookmarks', locals: { post: @post } %>
      </div>
    </div>

    <div class="author-info">
      <div clas="author-metadata">
        <%= avatar_for @post.user, size: 50 %>
        <div class="username-description">
          <h4><%= @post.user.username %></h4>
          <p><%= @post.user.description %></p>
        </div>
      </div>
      <%= follow_button_for @post.user %>
    </div>

    <% if user_signed_in? && current_user?(@post.user) %>
      <div class="edit-delete-button-wrapper">
        <%= link_to "Edit", edit_post_path(@post), class: 'button' %>
        <%= link_to "Delete", post_path(@post), method: :delete, class: 'button' %>
      </div>
    <% end %>
  </div>
</div> 

<div class="post-show-footer row" data-animation="fadeInUp-fadeOutDown">
  <% if @related_posts.any? %>
    <div class="col-xs-10 col-md-6 col-xs-offset-1 col-md-offset-3 main-content related-bonga">
      <h4 class="small-heading">Related bonga</h4>
      <% @related_posts.each do |post| %>
        <%= render partial: 'posts/post_list_item', locals: { post: post } %>
      <% end %>
    </div>
  <% end %>

  <div id="responses" class="col-xs-10 col-md-6 col-xs-offset-1 col-md-offset-3 main-content">
    <h4 class="small-heading">Responses</h4>
    <% if user_signed_in? %>
      <%= render partial: 'posts/response_editor', locals: { post: @post } %>
    <% end %>

    <div data-behavior="responses-list">
      <% if @responses.any? %>
          <%= render @responses %>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: 'posts/metadata_bar', locals: { post: @post } %>